// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#include "Protocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR S_INSIDE::S_INSIDE(
    ::_pbi::ConstantInitialized) {}
struct S_INSIDEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_INSIDEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_INSIDEDefaultTypeInternal() {}
  union {
    S_INSIDE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_INSIDEDefaultTypeInternal _S_INSIDE_default_instance_;
PROTOBUF_CONSTEXPR C_INSIDE::C_INSIDE(
    ::_pbi::ConstantInitialized) {}
struct C_INSIDEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_INSIDEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_INSIDEDefaultTypeInternal() {}
  union {
    C_INSIDE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_INSIDEDefaultTypeInternal _C_INSIDE_default_instance_;
PROTOBUF_CONSTEXPR S_OUTSIDE::S_OUTSIDE(
    ::_pbi::ConstantInitialized) {}
struct S_OUTSIDEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_OUTSIDEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_OUTSIDEDefaultTypeInternal() {}
  union {
    S_OUTSIDE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_OUTSIDEDefaultTypeInternal _S_OUTSIDE_default_instance_;
PROTOBUF_CONSTEXPR C_OUTSIDE::C_OUTSIDE(
    ::_pbi::ConstantInitialized) {}
struct C_OUTSIDEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_OUTSIDEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_OUTSIDEDefaultTypeInternal() {}
  union {
    C_OUTSIDE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_OUTSIDEDefaultTypeInternal _C_OUTSIDE_default_instance_;
PROTOBUF_CONSTEXPR S_START::S_START(
    ::_pbi::ConstantInitialized) {}
struct S_STARTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_STARTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_STARTDefaultTypeInternal() {}
  union {
    S_START _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_STARTDefaultTypeInternal _S_START_default_instance_;
PROTOBUF_CONSTEXPR C_START::C_START(
    ::_pbi::ConstantInitialized) {}
struct C_STARTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_STARTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_STARTDefaultTypeInternal() {}
  union {
    C_START _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_STARTDefaultTypeInternal _C_START_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Protocol_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Protocol_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Protocol_2eproto = nullptr;

const uint32_t TableStruct_Protocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_INSIDE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_INSIDE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_OUTSIDE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_OUTSIDE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_START, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_START, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::S_INSIDE)},
  { 6, -1, -1, sizeof(::Protocol::C_INSIDE)},
  { 12, -1, -1, sizeof(::Protocol::S_OUTSIDE)},
  { 18, -1, -1, sizeof(::Protocol::C_OUTSIDE)},
  { 24, -1, -1, sizeof(::Protocol::S_START)},
  { 30, -1, -1, sizeof(::Protocol::C_START)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_S_INSIDE_default_instance_._instance,
  &::Protocol::_C_INSIDE_default_instance_._instance,
  &::Protocol::_S_OUTSIDE_default_instance_._instance,
  &::Protocol::_C_OUTSIDE_default_instance_._instance,
  &::Protocol::_S_START_default_instance_._instance,
  &::Protocol::_C_START_default_instance_._instance,
};

const char descriptor_table_protodef_Protocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016Protocol.proto\022\010Protocol\032\nEnum.proto\"\n"
  "\n\010S_INSIDE\"\n\n\010C_INSIDE\"\013\n\tS_OUTSIDE\"\013\n\tC"
  "_OUTSIDE\"\t\n\007S_START\"\t\n\007C_STARTb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Protocol_2eproto_deps[1] = {
  &::descriptor_table_Enum_2eproto,
};
static ::_pbi::once_flag descriptor_table_Protocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Protocol_2eproto = {
    false, false, 118, descriptor_table_protodef_Protocol_2eproto,
    "Protocol.proto",
    &descriptor_table_Protocol_2eproto_once, descriptor_table_Protocol_2eproto_deps, 1, 6,
    schemas, file_default_instances, TableStruct_Protocol_2eproto::offsets,
    file_level_metadata_Protocol_2eproto, file_level_enum_descriptors_Protocol_2eproto,
    file_level_service_descriptors_Protocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Protocol_2eproto_getter() {
  return &descriptor_table_Protocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Protocol_2eproto(&descriptor_table_Protocol_2eproto);
namespace Protocol {

// ===================================================================

class S_INSIDE::_Internal {
 public:
};

S_INSIDE::S_INSIDE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S_INSIDE)
}
S_INSIDE::S_INSIDE(const S_INSIDE& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S_INSIDE* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S_INSIDE)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_INSIDE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_INSIDE::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S_INSIDE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[0]);
}

// ===================================================================

class C_INSIDE::_Internal {
 public:
};

C_INSIDE::C_INSIDE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.C_INSIDE)
}
C_INSIDE::C_INSIDE(const C_INSIDE& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  C_INSIDE* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C_INSIDE)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_INSIDE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_INSIDE::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C_INSIDE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[1]);
}

// ===================================================================

class S_OUTSIDE::_Internal {
 public:
};

S_OUTSIDE::S_OUTSIDE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S_OUTSIDE)
}
S_OUTSIDE::S_OUTSIDE(const S_OUTSIDE& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S_OUTSIDE* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S_OUTSIDE)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_OUTSIDE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_OUTSIDE::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S_OUTSIDE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[2]);
}

// ===================================================================

class C_OUTSIDE::_Internal {
 public:
};

C_OUTSIDE::C_OUTSIDE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.C_OUTSIDE)
}
C_OUTSIDE::C_OUTSIDE(const C_OUTSIDE& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  C_OUTSIDE* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C_OUTSIDE)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_OUTSIDE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_OUTSIDE::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C_OUTSIDE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[3]);
}

// ===================================================================

class S_START::_Internal {
 public:
};

S_START::S_START(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S_START)
}
S_START::S_START(const S_START& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S_START* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S_START)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_START::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_START::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S_START::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[4]);
}

// ===================================================================

class C_START::_Internal {
 public:
};

C_START::C_START(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.C_START)
}
C_START::C_START(const C_START& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  C_START* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C_START)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_START::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_START::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C_START::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocol_2eproto_getter, &descriptor_table_Protocol_2eproto_once,
      file_level_metadata_Protocol_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::S_INSIDE*
Arena::CreateMaybeMessage< ::Protocol::S_INSIDE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_INSIDE >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C_INSIDE*
Arena::CreateMaybeMessage< ::Protocol::C_INSIDE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C_INSIDE >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_OUTSIDE*
Arena::CreateMaybeMessage< ::Protocol::S_OUTSIDE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_OUTSIDE >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C_OUTSIDE*
Arena::CreateMaybeMessage< ::Protocol::C_OUTSIDE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C_OUTSIDE >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_START*
Arena::CreateMaybeMessage< ::Protocol::S_START >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_START >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C_START*
Arena::CreateMaybeMessage< ::Protocol::C_START >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C_START >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
